CREATE DATABASE IF NOT EXISTS tahiti;
CREATE DATABASE IF NOT EXISTS limonero;
CREATE DATABASE IF NOT EXISTS stand;
CREATE DATABASE IF NOT EXISTS caipirinha;
CREATE DATABASE IF NOT EXISTS thorn;
CREATE DATABASE IF NOT EXISTS seed;

